-- Generado por scripts/generar-seed.mjs — no editar a mano.

insert into ubicaciones_cr (provincia, canton, distrito) values
  ('Alajuela', 'Alajuela', 'Alajuela'),
  ('Alajuela', 'Alajuela', 'Carrizal'),
  ('Alajuela', 'Alajuela', 'Desamparados'),
  ('Alajuela', 'Alajuela', 'Garita'),
  ('Alajuela', 'Alajuela', 'Guácima'),
  ('Alajuela', 'Alajuela', 'Río Segundo'),
  ('Alajuela', 'Alajuela', 'Sabanilla'),
  ('Alajuela', 'Alajuela', 'San Antonio'),
  ('Alajuela', 'Alajuela', 'San Isidro'),
  ('Alajuela', 'Alajuela', 'San José'),
  ('Alajuela', 'Alajuela', 'San Rafael'),
  ('Alajuela', 'Alajuela', 'Sarapiquí'),
  ('Alajuela', 'Alajuela', 'Tambor'),
  ('Alajuela', 'Alajuela', 'Turrúcares'),
  ('Alajuela', 'Atenas', 'Atenas'),
  ('Alajuela', 'Atenas', 'Concepción'),
  ('Alajuela', 'Atenas', 'Escobal'),
  ('Alajuela', 'Atenas', 'Jesús'),
  ('Alajuela', 'Atenas', 'Mercedes'),
  ('Alajuela', 'Atenas', 'San Isidro'),
  ('Alajuela', 'Atenas', 'San José'),
  ('Alajuela', 'Atenas', 'Santa Eulalia'),
  ('Alajuela', 'Grecia', 'Bolivar'),
  ('Alajuela', 'Grecia', 'Grecia'),
  ('Alajuela', 'Grecia', 'Puente de Piedra'),
  ('Alajuela', 'Grecia', 'San Isidro'),
  ('Alajuela', 'Grecia', 'San José'),
  ('Alajuela', 'Grecia', 'San Roque'),
  ('Alajuela', 'Grecia', 'Tacares'),
  ('Alajuela', 'Guatuso', 'Buenavista'),
  ('Alajuela', 'Guatuso', 'Cote'),
  ('Alajuela', 'Guatuso', 'Katira'),
  ('Alajuela', 'Guatuso', 'San Rafael'),
  ('Alajuela', 'Los Chiles', 'Caño Negro'),
  ('Alajuela', 'Los Chiles', 'El Amparo'),
  ('Alajuela', 'Los Chiles', 'Los Chiles'),
  ('Alajuela', 'Los Chiles', 'San Jorge'),
  ('Alajuela', 'Naranjo', 'Cirrí Sur'),
  ('Alajuela', 'Naranjo', 'El Rosario'),
  ('Alajuela', 'Naranjo', 'Naranjo'),
  ('Alajuela', 'Naranjo', 'Palmitos'),
  ('Alajuela', 'Naranjo', 'San Jerónimo'),
  ('Alajuela', 'Naranjo', 'San José'),
  ('Alajuela', 'Naranjo', 'San Juan'),
  ('Alajuela', 'Naranjo', 'San Miguel'),
  ('Alajuela', 'Orotina', 'Coyolar'),
  ('Alajuela', 'Orotina', 'El Mastate'),
  ('Alajuela', 'Orotina', 'Hacienda Vieja'),
  ('Alajuela', 'Orotina', 'La Ceiba'),
  ('Alajuela', 'Orotina', 'Orotina'),
  ('Alajuela', 'Palmares', 'Buenos Aires'),
  ('Alajuela', 'Palmares', 'Candelaria'),
  ('Alajuela', 'Palmares', 'Esquipulas'),
  ('Alajuela', 'Palmares', 'La Granja'),
  ('Alajuela', 'Palmares', 'Palmares'),
  ('Alajuela', 'Palmares', 'Santiago'),
  ('Alajuela', 'Palmares', 'Zaragoza'),
  ('Alajuela', 'Poás', 'Carrillos'),
  ('Alajuela', 'Poás', 'Sabana Redonda'),
  ('Alajuela', 'Poás', 'San Juan'),
  ('Alajuela', 'Poás', 'San Pedro'),
  ('Alajuela', 'Poás', 'San Rafael'),
  ('Alajuela', 'Río Cuarto', 'Río Cuarto'),
  ('Alajuela', 'Río Cuarto', 'Santa Isabel'),
  ('Alajuela', 'Río Cuarto', 'Santa Rita'),
  ('Alajuela', 'San Carlos', 'Aguas Zarcas'),
  ('Alajuela', 'San Carlos', 'Buenavista'),
  ('Alajuela', 'San Carlos', 'Cutris'),
  ('Alajuela', 'San Carlos', 'Florencia'),
  ('Alajuela', 'San Carlos', 'La Fortuna'),
  ('Alajuela', 'San Carlos', 'La Palmera'),
  ('Alajuela', 'San Carlos', 'La Tigra'),
  ('Alajuela', 'San Carlos', 'Monterrey'),
  ('Alajuela', 'San Carlos', 'Pital'),
  ('Alajuela', 'San Carlos', 'Pocosol'),
  ('Alajuela', 'San Carlos', 'Quesada'),
  ('Alajuela', 'San Carlos', 'Venado'),
  ('Alajuela', 'San Carlos', 'Venecia'),
  ('Alajuela', 'San Mateo', 'Desmonte'),
  ('Alajuela', 'San Mateo', 'Jesús María'),
  ('Alajuela', 'San Mateo', 'Labrador'),
  ('Alajuela', 'San Mateo', 'San Mateo'),
  ('Alajuela', 'San Ramón', 'Alfaro'),
  ('Alajuela', 'San Ramón', 'Ángeles'),
  ('Alajuela', 'San Ramón', 'Concepción'),
  ('Alajuela', 'San Ramón', 'Peñas Blancas'),
  ('Alajuela', 'San Ramón', 'Piedades Norte'),
  ('Alajuela', 'San Ramón', 'Piedades Sur'),
  ('Alajuela', 'San Ramón', 'San Isidro'),
  ('Alajuela', 'San Ramón', 'San Juan'),
  ('Alajuela', 'San Ramón', 'San Lorenzo'),
  ('Alajuela', 'San Ramón', 'San Rafael'),
  ('Alajuela', 'San Ramón', 'San Ramón'),
  ('Alajuela', 'San Ramón', 'Santiago'),
  ('Alajuela', 'San Ramón', 'Volio'),
  ('Alajuela', 'San Ramón', 'Zapotal'),
  ('Alajuela', 'Sarchí', 'Rodríguez'),
  ('Alajuela', 'Sarchí', 'San Pedro'),
  ('Alajuela', 'Sarchí', 'Sarchí Norte'),
  ('Alajuela', 'Sarchí', 'Sarchí Sur'),
  ('Alajuela', 'Sarchí', 'Toro Amarillo'),
  ('Alajuela', 'Upala', 'Aguas Claras'),
  ('Alajuela', 'Upala', 'Bijagua'),
  ('Alajuela', 'Upala', 'Canalete'),
  ('Alajuela', 'Upala', 'Delicias'),
  ('Alajuela', 'Upala', 'Dos Ríos'),
  ('Alajuela', 'Upala', 'San José O Pizote'),
  ('Alajuela', 'Upala', 'Upala'),
  ('Alajuela', 'Upala', 'Yolillal'),
  ('Alajuela', 'Zarcero', 'Brisas'),
  ('Alajuela', 'Zarcero', 'Guadalupe'),
  ('Alajuela', 'Zarcero', 'Laguna'),
  ('Alajuela', 'Zarcero', 'Palmira'),
  ('Alajuela', 'Zarcero', 'Tapesco'),
  ('Alajuela', 'Zarcero', 'Zapote'),
  ('Alajuela', 'Zarcero', 'Zarcero'),
  ('Cartago', 'Alvarado', 'Capellades'),
  ('Cartago', 'Alvarado', 'Cervantes'),
  ('Cartago', 'Alvarado', 'Pacayas'),
  ('Cartago', 'Cartago', 'Aguacaliente o San Francisco'),
  ('Cartago', 'Cartago', 'Carmen'),
  ('Cartago', 'Cartago', 'Corralillo'),
  ('Cartago', 'Cartago', 'Dulce Nombre'),
  ('Cartago', 'Cartago', 'Guadalupe o Arenilla'),
  ('Cartago', 'Cartago', 'Llano Grande'),
  ('Cartago', 'Cartago', 'Occidental'),
  ('Cartago', 'Cartago', 'Oriental'),
  ('Cartago', 'Cartago', 'Quebradilla'),
  ('Cartago', 'Cartago', 'San Nicolás'),
  ('Cartago', 'Cartago', 'Tierra Blanca'),
  ('Cartago', 'El Guarco', 'El Tejar'),
  ('Cartago', 'El Guarco', 'Patio de Agua'),
  ('Cartago', 'El Guarco', 'San Isidro'),
  ('Cartago', 'El Guarco', 'Tobosi'),
  ('Cartago', 'Jiménez', 'Juan Viñas'),
  ('Cartago', 'Jiménez', 'La Victoria'),
  ('Cartago', 'Jiménez', 'Pejibaye'),
  ('Cartago', 'Jiménez', 'Tucurrique'),
  ('Cartago', 'La Unión', 'Concepción'),
  ('Cartago', 'La Unión', 'Dulce Nombre'),
  ('Cartago', 'La Unión', 'Río Azul'),
  ('Cartago', 'La Unión', 'San Diego'),
  ('Cartago', 'La Unión', 'San Juan'),
  ('Cartago', 'La Unión', 'San Rafael'),
  ('Cartago', 'La Unión', 'San Ramón'),
  ('Cartago', 'La Unión', 'Tres Ríos'),
  ('Cartago', 'Oreamuno', 'Cipreses'),
  ('Cartago', 'Oreamuno', 'Cot'),
  ('Cartago', 'Oreamuno', 'Potrero Cerrado'),
  ('Cartago', 'Oreamuno', 'San Rafael'),
  ('Cartago', 'Oreamuno', 'Santa Rosa'),
  ('Cartago', 'Paraíso', 'Birrisito'),
  ('Cartago', 'Paraíso', 'Cachí'),
  ('Cartago', 'Paraíso', 'Llanos de Santa Lucía'),
  ('Cartago', 'Paraíso', 'Orosi'),
  ('Cartago', 'Paraíso', 'Paraíso'),
  ('Cartago', 'Paraíso', 'Santiago'),
  ('Cartago', 'Turrialba', 'Chirripó'),
  ('Cartago', 'Turrialba', 'La Isabel'),
  ('Cartago', 'Turrialba', 'La Suiza'),
  ('Cartago', 'Turrialba', 'Pavones'),
  ('Cartago', 'Turrialba', 'Peralta'),
  ('Cartago', 'Turrialba', 'Santa Cruz'),
  ('Cartago', 'Turrialba', 'Santa Rosa'),
  ('Cartago', 'Turrialba', 'Santa Teresita'),
  ('Cartago', 'Turrialba', 'Tayutic'),
  ('Cartago', 'Turrialba', 'Tres Equis'),
  ('Cartago', 'Turrialba', 'Tuis'),
  ('Cartago', 'Turrialba', 'Turrialba'),
  ('Guanacaste', 'Abangares', 'Colorado'),
  ('Guanacaste', 'Abangares', 'Las Juntas'),
  ('Guanacaste', 'Abangares', 'San Juan'),
  ('Guanacaste', 'Abangares', 'Sierra'),
  ('Guanacaste', 'Bagaces', 'Bagaces'),
  ('Guanacaste', 'Bagaces', 'La Fortuna'),
  ('Guanacaste', 'Bagaces', 'Mogote'),
  ('Guanacaste', 'Bagaces', 'Río Naranjo'),
  ('Guanacaste', 'Cañas', 'Bebedero'),
  ('Guanacaste', 'Cañas', 'Cañas'),
  ('Guanacaste', 'Cañas', 'Palmira'),
  ('Guanacaste', 'Cañas', 'Porozal'),
  ('Guanacaste', 'Cañas', 'San Miguel'),
  ('Guanacaste', 'Carrillo', 'Belén'),
  ('Guanacaste', 'Carrillo', 'Filadelfia'),
  ('Guanacaste', 'Carrillo', 'Palmira'),
  ('Guanacaste', 'Carrillo', 'Sardinal'),
  ('Guanacaste', 'Hojancha', 'Hojancha'),
  ('Guanacaste', 'Hojancha', 'Huacas'),
  ('Guanacaste', 'Hojancha', 'Matambú'),
  ('Guanacaste', 'Hojancha', 'Monte Romo'),
  ('Guanacaste', 'Hojancha', 'Puerto Carrillo'),
  ('Guanacaste', 'La Cruz', 'La Cruz'),
  ('Guanacaste', 'La Cruz', 'La Garita'),
  ('Guanacaste', 'La Cruz', 'Santa Cecilia'),
  ('Guanacaste', 'La Cruz', 'Santa Elena'),
  ('Guanacaste', 'Liberia', 'Cañas Dulces'),
  ('Guanacaste', 'Liberia', 'Curubandé'),
  ('Guanacaste', 'Liberia', 'Liberia'),
  ('Guanacaste', 'Liberia', 'Mayorga'),
  ('Guanacaste', 'Liberia', 'Nacascolo'),
  ('Guanacaste', 'Nandayure', 'Bejuco'),
  ('Guanacaste', 'Nandayure', 'Carmona'),
  ('Guanacaste', 'Nandayure', 'Porvenir'),
  ('Guanacaste', 'Nandayure', 'San Pablo'),
  ('Guanacaste', 'Nandayure', 'Santa Rita'),
  ('Guanacaste', 'Nandayure', 'Zapotal'),
  ('Guanacaste', 'Nicoya', 'Belén de Nosarita'),
  ('Guanacaste', 'Nicoya', 'Mansión'),
  ('Guanacaste', 'Nicoya', 'Nicoya'),
  ('Guanacaste', 'Nicoya', 'Nosara'),
  ('Guanacaste', 'Nicoya', 'Quebrada Honda'),
  ('Guanacaste', 'Nicoya', 'Sámara'),
  ('Guanacaste', 'Nicoya', 'San Antonio'),
  ('Guanacaste', 'Santa Cruz', 'Bolsón'),
  ('Guanacaste', 'Santa Cruz', 'Cabo Velas'),
  ('Guanacaste', 'Santa Cruz', 'Cartagena'),
  ('Guanacaste', 'Santa Cruz', 'Cuajiniquil'),
  ('Guanacaste', 'Santa Cruz', 'Diriá'),
  ('Guanacaste', 'Santa Cruz', 'Santa Cruz'),
  ('Guanacaste', 'Santa Cruz', 'Tamarindo'),
  ('Guanacaste', 'Santa Cruz', 'Tempate'),
  ('Guanacaste', 'Santa Cruz', 'Veintisiete de Abril'),
  ('Guanacaste', 'Tilarán', 'Arenal'),
  ('Guanacaste', 'Tilarán', 'Cabeceras'),
  ('Guanacaste', 'Tilarán', 'Líbano'),
  ('Guanacaste', 'Tilarán', 'Quebrada Grande'),
  ('Guanacaste', 'Tilarán', 'Santa Rosa'),
  ('Guanacaste', 'Tilarán', 'Tierras Morenas'),
  ('Guanacaste', 'Tilarán', 'Tilarán'),
  ('Guanacaste', 'Tilarán', 'Tronadora'),
  ('Heredia', 'Barva', 'Barva'),
  ('Heredia', 'Barva', 'Puente Salas'),
  ('Heredia', 'Barva', 'San José de la Montaña'),
  ('Heredia', 'Barva', 'San Pablo'),
  ('Heredia', 'Barva', 'San Pedro'),
  ('Heredia', 'Barva', 'San Roque'),
  ('Heredia', 'Barva', 'Santa Lucía'),
  ('Heredia', 'Belén', 'La Asunción'),
  ('Heredia', 'Belén', 'La Ribera'),
  ('Heredia', 'Belén', 'San Antonio'),
  ('Heredia', 'Flores', 'Barrantes'),
  ('Heredia', 'Flores', 'Llorente'),
  ('Heredia', 'Flores', 'San Joaquín'),
  ('Heredia', 'Heredia', 'Heredia'),
  ('Heredia', 'Heredia', 'Mercedes'),
  ('Heredia', 'Heredia', 'San Francisco'),
  ('Heredia', 'Heredia', 'Ulloa'),
  ('Heredia', 'Heredia', 'Varablanca'),
  ('Heredia', 'San Isidro', 'Concepción'),
  ('Heredia', 'San Isidro', 'San Francisco'),
  ('Heredia', 'San Isidro', 'San Isidro'),
  ('Heredia', 'San Isidro', 'San José'),
  ('Heredia', 'San Pablo', 'Rincón de Sabanilla'),
  ('Heredia', 'San Pablo', 'San Pablo'),
  ('Heredia', 'San Rafael', 'Ángeles'),
  ('Heredia', 'San Rafael', 'Concepción'),
  ('Heredia', 'San Rafael', 'San Josecito'),
  ('Heredia', 'San Rafael', 'San Rafael'),
  ('Heredia', 'San Rafael', 'Santiago'),
  ('Heredia', 'Santa Bárbara', 'Jesús'),
  ('Heredia', 'Santa Bárbara', 'Purabá'),
  ('Heredia', 'Santa Bárbara', 'San Juan'),
  ('Heredia', 'Santa Bárbara', 'San Pedro'),
  ('Heredia', 'Santa Bárbara', 'Santa Bárbara'),
  ('Heredia', 'Santa Bárbara', 'Santo Domingo'),
  ('Heredia', 'Santo Domingo', 'Pará'),
  ('Heredia', 'Santo Domingo', 'Paracito'),
  ('Heredia', 'Santo Domingo', 'San Miguel'),
  ('Heredia', 'Santo Domingo', 'San Vicente'),
  ('Heredia', 'Santo Domingo', 'Santa Rosa'),
  ('Heredia', 'Santo Domingo', 'Santo Domingo'),
  ('Heredia', 'Santo Domingo', 'Santo Tomás'),
  ('Heredia', 'Santo Domingo', 'Tures'),
  ('Heredia', 'Sarapiquí', 'Cureña'),
  ('Heredia', 'Sarapiquí', 'La Virgen'),
  ('Heredia', 'Sarapiquí', 'Las Horquetas'),
  ('Heredia', 'Sarapiquí', 'Llanuras del Gaspar'),
  ('Heredia', 'Sarapiquí', 'Puerto Viejo'),
  ('Limón', 'Guácimo', 'Duacarí'),
  ('Limón', 'Guácimo', 'Guácimo'),
  ('Limón', 'Guácimo', 'Mercedes'),
  ('Limón', 'Guácimo', 'Pocora'),
  ('Limón', 'Guácimo', 'Río Jiménez'),
  ('Limón', 'Limón', 'Limón'),
  ('Limón', 'Limón', 'Matama'),
  ('Limón', 'Limón', 'Río Blanco'),
  ('Limón', 'Limón', 'Valle La Estrella'),
  ('Limón', 'Matina', 'Batán'),
  ('Limón', 'Matina', 'Carrandí'),
  ('Limón', 'Matina', 'Matina'),
  ('Limón', 'Pococí', 'Cariari'),
  ('Limón', 'Pococí', 'Colorado'),
  ('Limón', 'Pococí', 'Guápiles'),
  ('Limón', 'Pococí', 'Jiménez'),
  ('Limón', 'Pococí', 'La Colonia'),
  ('Limón', 'Pococí', 'Rita'),
  ('Limón', 'Pococí', 'Roxana'),
  ('Limón', 'Siquirres', 'Alegría'),
  ('Limón', 'Siquirres', 'El Cairo'),
  ('Limón', 'Siquirres', 'Florida'),
  ('Limón', 'Siquirres', 'Germania'),
  ('Limón', 'Siquirres', 'Pacuarito'),
  ('Limón', 'Siquirres', 'Reventazón'),
  ('Limón', 'Siquirres', 'Siquirres'),
  ('Limón', 'Talamanca', 'Bratsi'),
  ('Limón', 'Talamanca', 'Cahuita'),
  ('Limón', 'Talamanca', 'Sixaola'),
  ('Limón', 'Talamanca', 'Telire'),
  ('Puntarenas', 'Buenos Aires', 'Biolley'),
  ('Puntarenas', 'Buenos Aires', 'Boruca'),
  ('Puntarenas', 'Buenos Aires', 'Brunka'),
  ('Puntarenas', 'Buenos Aires', 'Buenos Aires'),
  ('Puntarenas', 'Buenos Aires', 'Chánguena'),
  ('Puntarenas', 'Buenos Aires', 'Colinas'),
  ('Puntarenas', 'Buenos Aires', 'Pilas'),
  ('Puntarenas', 'Buenos Aires', 'Potrero Grande'),
  ('Puntarenas', 'Buenos Aires', 'Volcán'),
  ('Puntarenas', 'Corredores', 'Canoas'),
  ('Puntarenas', 'Corredores', 'Corredor'),
  ('Puntarenas', 'Corredores', 'La Cuesta'),
  ('Puntarenas', 'Corredores', 'Laurel'),
  ('Puntarenas', 'Coto Brus', 'Aguabuena'),
  ('Puntarenas', 'Coto Brus', 'Gutiérrez Braun'),
  ('Puntarenas', 'Coto Brus', 'Limoncito'),
  ('Puntarenas', 'Coto Brus', 'Pittier'),
  ('Puntarenas', 'Coto Brus', 'Sabalito'),
  ('Puntarenas', 'Coto Brus', 'San Vito'),
  ('Puntarenas', 'Esparza', 'Caldera'),
  ('Puntarenas', 'Esparza', 'Espíritu Santo'),
  ('Puntarenas', 'Esparza', 'Macacona'),
  ('Puntarenas', 'Esparza', 'San Jerónimo'),
  ('Puntarenas', 'Esparza', 'San Juan Grande'),
  ('Puntarenas', 'Esparza', 'San Rafael'),
  ('Puntarenas', 'Garabito', 'Jacó'),
  ('Puntarenas', 'Garabito', 'Lagunillas'),
  ('Puntarenas', 'Garabito', 'Tárcoles'),
  ('Puntarenas', 'Golfito', 'Golfito'),
  ('Puntarenas', 'Golfito', 'Guaycará'),
  ('Puntarenas', 'Golfito', 'Pavón'),
  ('Puntarenas', 'Montes de Oro', 'La Unión'),
  ('Puntarenas', 'Montes de Oro', 'Miramar'),
  ('Puntarenas', 'Montes de Oro', 'San Isidro'),
  ('Puntarenas', 'Monteverde', 'Monteverde'),
  ('Puntarenas', 'Osa', 'Bahía Ballena'),
  ('Puntarenas', 'Osa', 'Bahía Drake'),
  ('Puntarenas', 'Osa', 'Palmar'),
  ('Puntarenas', 'Osa', 'Piedras Blancas'),
  ('Puntarenas', 'Osa', 'Puerto Cortés'),
  ('Puntarenas', 'Osa', 'Sierpe'),
  ('Puntarenas', 'Parrita', 'Parrita'),
  ('Puntarenas', 'Puerto Jiménez', 'Puerto Jiménez'),
  ('Puntarenas', 'Puntarenas', 'Acapulco'),
  ('Puntarenas', 'Puntarenas', 'Arancibia'),
  ('Puntarenas', 'Puntarenas', 'Barranca'),
  ('Puntarenas', 'Puntarenas', 'Chacarita'),
  ('Puntarenas', 'Puntarenas', 'Chira'),
  ('Puntarenas', 'Puntarenas', 'Chomes'),
  ('Puntarenas', 'Puntarenas', 'Cóbano'),
  ('Puntarenas', 'Puntarenas', 'El Roble'),
  ('Puntarenas', 'Puntarenas', 'Guacimal'),
  ('Puntarenas', 'Puntarenas', 'Isla del Coco'),
  ('Puntarenas', 'Puntarenas', 'Lepanto'),
  ('Puntarenas', 'Puntarenas', 'Manzanillo'),
  ('Puntarenas', 'Puntarenas', 'Paquera'),
  ('Puntarenas', 'Puntarenas', 'Pitahaya'),
  ('Puntarenas', 'Puntarenas', 'Puntarenas'),
  ('Puntarenas', 'Quepos', 'Naranjito'),
  ('Puntarenas', 'Quepos', 'Quepos'),
  ('Puntarenas', 'Quepos', 'Savegre'),
  ('San José', 'Acosta', 'Cangrejal'),
  ('San José', 'Acosta', 'Guaitil'),
  ('San José', 'Acosta', 'Palmichal'),
  ('San José', 'Acosta', 'Sabanillas'),
  ('San José', 'Acosta', 'San Ignacio'),
  ('San José', 'Alajuelita', 'Alajuelita'),
  ('San José', 'Alajuelita', 'Concepción'),
  ('San José', 'Alajuelita', 'San Antonio'),
  ('San José', 'Alajuelita', 'San Felipe'),
  ('San José', 'Alajuelita', 'San Josecito'),
  ('San José', 'Aserrí', 'Aserrí'),
  ('San José', 'Aserrí', 'Legua'),
  ('San José', 'Aserrí', 'Monterrey'),
  ('San José', 'Aserrí', 'Salitrillos'),
  ('San José', 'Aserrí', 'San Gabriel'),
  ('San José', 'Aserrí', 'Tarbaca'),
  ('San José', 'Aserrí', 'Vuelta de Jorco'),
  ('San José', 'Curridabat', 'Curridabat'),
  ('San José', 'Curridabat', 'Granadilla'),
  ('San José', 'Curridabat', 'Sánchez'),
  ('San José', 'Curridabat', 'Tirrases'),
  ('San José', 'Desamparados', 'Damas'),
  ('San José', 'Desamparados', 'Desamparados'),
  ('San José', 'Desamparados', 'Frailes'),
  ('San José', 'Desamparados', 'Gravilias'),
  ('San José', 'Desamparados', 'Los Guido'),
  ('San José', 'Desamparados', 'Patarrá'),
  ('San José', 'Desamparados', 'Rosario'),
  ('San José', 'Desamparados', 'San Antonio'),
  ('San José', 'Desamparados', 'San Cristobal'),
  ('San José', 'Desamparados', 'San Juan de Dios'),
  ('San José', 'Desamparados', 'San Miguel'),
  ('San José', 'Desamparados', 'San Rafael Abajo'),
  ('San José', 'Desamparados', 'San Rafael Arriba'),
  ('San José', 'Dota', 'Copey'),
  ('San José', 'Dota', 'Jardín'),
  ('San José', 'Dota', 'Santa María'),
  ('San José', 'Escazú', 'Escazú'),
  ('San José', 'Escazú', 'San Antonio'),
  ('San José', 'Escazú', 'San Rafael'),
  ('San José', 'Goicoechea', 'Calle Blancos'),
  ('San José', 'Goicoechea', 'Guadalupe'),
  ('San José', 'Goicoechea', 'Ipís'),
  ('San José', 'Goicoechea', 'Mata de Plátano'),
  ('San José', 'Goicoechea', 'Purral'),
  ('San José', 'Goicoechea', 'Rancho Redondo'),
  ('San José', 'Goicoechea', 'San Francisco'),
  ('San José', 'León Cortés Castro', 'Llano Bonito'),
  ('San José', 'León Cortés Castro', 'San Andrés'),
  ('San José', 'León Cortés Castro', 'San Antonio'),
  ('San José', 'León Cortés Castro', 'San Isidro'),
  ('San José', 'León Cortés Castro', 'San Pablo'),
  ('San José', 'León Cortés Castro', 'Santa Cruz'),
  ('San José', 'Montes de Oca', 'Mercedes'),
  ('San José', 'Montes de Oca', 'Sabanilla'),
  ('San José', 'Montes de Oca', 'San Pedro'),
  ('San José', 'Montes de Oca', 'San Rafael'),
  ('San José', 'Mora', 'Colón'),
  ('San José', 'Mora', 'Guayabo'),
  ('San José', 'Mora', 'Jaris'),
  ('San José', 'Mora', 'Picagres'),
  ('San José', 'Mora', 'Piedras Negras'),
  ('San José', 'Mora', 'Quitirrisí'),
  ('San José', 'Mora', 'Tabarcia'),
  ('San José', 'Moravia', 'La Trinidad'),
  ('San José', 'Moravia', 'San Jerónimo'),
  ('San José', 'Moravia', 'San Vicente'),
  ('San José', 'Pérez Zeledón', 'Barú'),
  ('San José', 'Pérez Zeledón', 'Cajón'),
  ('San José', 'Pérez Zeledón', 'Daniel Flores'),
  ('San José', 'Pérez Zeledón', 'El General'),
  ('San José', 'Pérez Zeledón', 'La  Amistad'),
  ('San José', 'Pérez Zeledón', 'Páramo'),
  ('San José', 'Pérez Zeledón', 'Pejibaye'),
  ('San José', 'Pérez Zeledón', 'Platanares'),
  ('San José', 'Pérez Zeledón', 'Río Nuevo'),
  ('San José', 'Pérez Zeledón', 'Rivas'),
  ('San José', 'Pérez Zeledón', 'San Isidro de El General'),
  ('San José', 'Pérez Zeledón', 'San Pedro'),
  ('San José', 'Puriscal', 'Barbacoas'),
  ('San José', 'Puriscal', 'Candelarita'),
  ('San José', 'Puriscal', 'Chires'),
  ('San José', 'Puriscal', 'Desamparaditos'),
  ('San José', 'Puriscal', 'Grifo Alto'),
  ('San José', 'Puriscal', 'Mercedes Sur'),
  ('San José', 'Puriscal', 'San Antonio'),
  ('San José', 'Puriscal', 'San Rafael'),
  ('San José', 'Puriscal', 'Santiago'),
  ('San José', 'San José', 'Carmen'),
  ('San José', 'San José', 'Catedral'),
  ('San José', 'San José', 'Hatillo'),
  ('San José', 'San José', 'Hospital'),
  ('San José', 'San José', 'Mata Redonda'),
  ('San José', 'San José', 'Merced'),
  ('San José', 'San José', 'Pavas'),
  ('San José', 'San José', 'San Francisco de Dos Ríos'),
  ('San José', 'San José', 'San Sebastián'),
  ('San José', 'San José', 'Uruca'),
  ('San José', 'San José', 'Zapote'),
  ('San José', 'Santa Ana', 'Brasil'),
  ('San José', 'Santa Ana', 'Piedades'),
  ('San José', 'Santa Ana', 'Pozos'),
  ('San José', 'Santa Ana', 'Salitral'),
  ('San José', 'Santa Ana', 'Santa Ana'),
  ('San José', 'Santa Ana', 'Uruca'),
  ('San José', 'Tarrazú', 'San Carlos'),
  ('San José', 'Tarrazú', 'San Lorenzo'),
  ('San José', 'Tarrazú', 'San Marcos'),
  ('San José', 'Tibás', 'Anselmo Llorente'),
  ('San José', 'Tibás', 'Cinco Esquinas'),
  ('San José', 'Tibás', 'Colima'),
  ('San José', 'Tibás', 'León XIII'),
  ('San José', 'Tibás', 'San Juan'),
  ('San José', 'Turrubares', 'Carara'),
  ('San José', 'Turrubares', 'San Juan de Mata'),
  ('San José', 'Turrubares', 'San Luis'),
  ('San José', 'Turrubares', 'San Pablo'),
  ('San José', 'Turrubares', 'San Pedro'),
  ('San José', 'Vázquez de Coronado', 'Cascajal'),
  ('San José', 'Vázquez de Coronado', 'Dulce Nombre de Jesús'),
  ('San José', 'Vázquez de Coronado', 'Patalillo'),
  ('San José', 'Vázquez de Coronado', 'San Isidro'),
  ('San José', 'Vázquez de Coronado', 'San Rafael');

insert into regionales (nombre, orden) values
  ('Dirección Regional I San José', 1),
  ('Dirección Regional II Cartago', 2),
  ('Dirección Regional III Alajuela', 3),
  ('Macro Región IV San Carlos', 4),
  ('Dirección Regional V Heredia', 5),
  ('Macro Región  VI Guanacaste', 6),
  ('Dirección Regional VIII Sandoval', 7),
  ('Dirección Regional IX Guácimo', 8),
  ('Dirección Regional X Pérez Zeledón', 9),
  ('Dirección Regional  XI Río Claro', 10),
  ('Macro Región XII Pacífico Central', 11)
on conflict do nothing;
